### ISSUE TITLE
Regarding the issues you asked about on IRC

### ISSUE THREAD

**Issue by maruohon** [thislooksfun/NBTReader#1]
There are several things about your code/logic that I don't understand, why you are doing them this way. I would prefer discussing them in more detail on IRC sometime (nick: masa).

For example:
- Why are you using custom packets for all the TE syncing?
- Why don't you use getDescriptionPacket() and onDataPacket() at all?
- I don't understand your updateClients(), updateAll() etc logic. Why are you doing some stuff on the client side, like markDirty()? ( ALL logic/stuff should only happen on the server side and from there get synced to clients who need some of the data for something like rendering)
- Why do you need an updateAll() method, that apparently syncs something from the client to the server? What are you doing on the client side and why?
- You don't seem to mark for updates when changes actually happen. Instead you seem to do stuff every 5 ticks, which includes syncing everything to clients every 5 ticks regardless of if anything changed.
- You also seem to recreate the Coords object each time you call pullItems(), although it never changes (right?). Why not create it once when it doesn't exist?
- What I do, is I check when data that actually affects the client (for example rendering) changes, I only then call this.worldObj.markBlockForUpdate(). That causes the getDescriptionPacket() to send the data, and onDataPacket() on the client receives it.
- For reference, my current (messy) code: https://github.com/maruohon/enderutilities/blob/master/src/main/java/fi/dy/masa/enderutilities/tileentity/TileEntityEnderFurnace.java

**Comment by thislooksfun** [comment]
Answering in order:
- I have a GUI on the client (obviously), and I'm trying to sync the changes from that over to the server-side.
- Because I was trying to have Delta syncing, as the packets could get quite big with all the matching rules (the ArrayList<ArrayList<String>>)
- I had those so I could just send part of the update to the server in an update, as mentioned above. The markDirty is actually a good point though, I didn't catch that.
- See the first point.
- Yes, I am running code every 5 ticks, but it doesn't fire any packets.
- If you look, I am not actually creating a new one. That is a safety method, because some of the code that needs the coord information gets run before the world/position information is set. If you actually read the getPos() method, you'll see that it only creates a new one if there isn't one already, the worldObj isn't null, and the yPos > -1 (because I set the yPos to be -1 in the constructor, so this check would work)
- Ok, but why isn't Minecraft.getMinecraft().renderGlobal.markBlockForRenderUpdate working then?

P.S. Sorry if I sound like a smart-ass in some of these. I'm just frustrated by this.

EDIT: The DataPacket thing _seems_ to be working, but I need to get the GUI button presses on the server side. Know how to do that?

EDIT 2: I figured it out! Thanks for the pointers.
